// PreToolUse hook: stops edits to generated files and asks before edits to security-pinned ones.
// Reads the tool call from stdin; prints a permission decision for matching paths, nothing otherwise.
import path from 'node:path';

const RULES = [
  {
    match: /^packages\/core\/drizzle\/meta\//,
    decision: 'deny',
    reason:
      'Drizzle snapshots and journal are generated. Edit packages/core/src/db/schema.ts and run `pnpm --filter @synoikia/core db:generate`.',
  },
  {
    match: /^packages\/core\/drizzle\/.*\.sql$/,
    decision: 'ask',
    reason:
      'Migration SQL is generated by drizzle-kit. Only append data-migration statements to the migration just generated; never edit one that has shipped.',
  },
  {
    match: /(^|\/)pnpm-lock\.yaml$/,
    decision: 'deny',
    reason: 'pnpm-lock.yaml is generated. Change package.json and run `pnpm install` instead.',
  },
  {
    match: /^packages\/core\/src\/plugins\/default-repo\.ts$/,
    decision: 'ask',
    reason:
      'default-repo.ts pins the synoikia-core-plugins signing key. Changing it marks every install `key_changed`; only for a compromised key.',
  },
];

let input = '';
for await (const chunk of process.stdin) input += chunk;
const { tool_input: toolInput = {}, cwd } = JSON.parse(input || '{}');
const file = toolInput.file_path ?? toolInput.notebook_path;
if (!file) process.exit(0);

const root = process.env.CLAUDE_PROJECT_DIR ?? cwd ?? process.cwd();
const rel = path.relative(root, path.resolve(root, file)).split(path.sep).join('/');
const rule = RULES.find((r) => r.match.test(rel));
if (!rule) process.exit(0);

console.log(
  JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: rule.decision,
      permissionDecisionReason: `${rel}: ${rule.reason}`,
    },
  }),
);
